//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FJ.Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string AccountUser { get; set; }
        public string Password { get; set; }
        public int IdentityCode { get; set; }
        public string Crt_User { get; set; }
        public Nullable<System.DateTime> Crt_Date { get; set; }
        public string Mdf_User { get; set; }
        public Nullable<System.DateTime> Mdf_Date { get; set; }
        public string UserName { get; set; }
        public Nullable<int> WineryId { get; set; }
    
        public virtual Winery Winery { get; set; }
    }
}
